#!/usr/bin/env bash
# Paperclip VPS bootstrap — fresh Ubuntu 24.04 to a TLS-fronted control plane.
#
# Usage:
#
#   PAPERCLIP_DOMAIN=paperclip.example.com ./bootstrap.sh
#
# Optional env:
#   PAPERCLIP_REF       git ref of paperclipai/paperclip to deploy (default: pinned in .env.template)
#   PAPERCLIP_HOME_DIR  install root for the cloned repo (default: /opt/paperclip)
#   DRY_RUN=1           print what would happen, do nothing
#
# What it does, in order:
#   1. Verifies you're root on Ubuntu 24.04 with the expected firewall posture.
#   2. Installs Docker Engine + Compose plugin if missing.
#   3. Clones paperclipai/paperclip at $PAPERCLIP_REF into $PAPERCLIP_HOME_DIR.
#   4. Drops in the production overlay, Caddyfile, and a generated .env.
#   5. Brings the stack up and waits for the server's first board-claim URL.
#
# The script is idempotent: re-running won't clobber an existing .env or
# overwrite already-cloned code. It will pick up where it left off.

set -euo pipefail

DRY_RUN="${DRY_RUN:-0}"
PAPERCLIP_HOME_DIR="${PAPERCLIP_HOME_DIR:-/opt/paperclip}"
PAPERCLIP_DOMAIN="${PAPERCLIP_DOMAIN:-}"
DEFAULT_REF="v2026.427.0"
PAPERCLIP_REF="${PAPERCLIP_REF:-$DEFAULT_REF}"

EXAMPLE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DOCKER_DIR="${PAPERCLIP_HOME_DIR}/docker"

log() { printf '\033[1;34m[bootstrap]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[bootstrap]\033[0m %s\n' "$*" >&2; }
die() { printf '\033[1;31m[bootstrap]\033[0m %s\n' "$*" >&2; exit 1; }
run() {
  if [ "$DRY_RUN" = "1" ]; then
    printf '\033[2m  + %s\033[0m\n' "$*"
  else
    eval "$@"
  fi
}

# ---- preflight ---------------------------------------------------------------

[ "$(id -u)" -eq 0 ] || die "must run as root (sudo -i first)"
[ -n "$PAPERCLIP_DOMAIN" ] || die "PAPERCLIP_DOMAIN is required (e.g. PAPERCLIP_DOMAIN=paperclip.example.com)"

if [ -r /etc/os-release ]; then
  . /etc/os-release
  if [ "${ID:-}" != "ubuntu" ] || [ "${VERSION_ID:-}" != "24.04" ]; then
    warn "tested on Ubuntu 24.04; detected ${PRETTY_NAME:-unknown} — proceeding anyway"
  fi
else
  warn "/etc/os-release not found — proceeding without OS check"
fi

if [ ! -d "$EXAMPLE_DIR/scripts" ] || [ ! -f "$EXAMPLE_DIR/Caddyfile" ]; then
  die "expected example files at $EXAMPLE_DIR (Caddyfile, .env.template, docker-compose.prod.yml)"
fi

# ---- docker ------------------------------------------------------------------

if ! command -v docker >/dev/null 2>&1; then
  log "installing Docker Engine via get.docker.com"
  run "curl -fsSL https://get.docker.com | sh"
fi

if ! docker compose version >/dev/null 2>&1; then
  log "installing docker-compose-plugin"
  run "apt-get update -qq"
  run "apt-get install -y docker-compose-plugin"
fi

# Compose v2.27+ is required for the `!reset` overlay tag.
COMPOSE_VERSION="$(docker compose version --short 2>/dev/null || echo 0.0.0)"
if [ "$(printf '%s\n2.27.0\n' "$COMPOSE_VERSION" | sort -V | head -n1)" != "2.27.0" ]; then
  warn "docker compose $COMPOSE_VERSION is older than 2.27 — overlay may merge ports instead of resetting them"
fi

# ---- clone -------------------------------------------------------------------

if [ ! -d "$PAPERCLIP_HOME_DIR/.git" ]; then
  log "cloning paperclipai/paperclip @ $PAPERCLIP_REF into $PAPERCLIP_HOME_DIR"
  run "git clone --depth 1 --branch '$PAPERCLIP_REF' https://github.com/paperclipai/paperclip '$PAPERCLIP_HOME_DIR'"
else
  current_ref="$(git -C "$PAPERCLIP_HOME_DIR" describe --tags --always 2>/dev/null || echo unknown)"
  if [ "$current_ref" != "$PAPERCLIP_REF" ]; then
    warn "$PAPERCLIP_HOME_DIR already exists at ref $current_ref (expected $PAPERCLIP_REF)"
    warn "leaving the checkout alone — bump it manually if this is a deploy"
  fi
fi

# ---- drop in overlay + Caddyfile --------------------------------------------

log "copying production overlay + Caddyfile into $DOCKER_DIR"
run "install -m 0644 '$EXAMPLE_DIR/docker-compose.prod.yml' '$DOCKER_DIR/docker-compose.prod.yml'"
run "install -m 0644 '$EXAMPLE_DIR/Caddyfile' '$DOCKER_DIR/Caddyfile'"

# ---- .env --------------------------------------------------------------------

ENV_FILE="$DOCKER_DIR/.env"
if [ -f "$ENV_FILE" ]; then
  log ".env already exists at $ENV_FILE — leaving secrets in place"
else
  log "generating $ENV_FILE with random secrets"
  better_auth_secret="$(openssl rand -hex 32)"
  postgres_password="$(openssl rand -hex 24)"
  if [ "$DRY_RUN" = "1" ]; then
    printf '\033[2m  + would write .env with PAPERCLIP_DOMAIN=%s, random BETTER_AUTH_SECRET, random POSTGRES_PASSWORD\033[0m\n' "$PAPERCLIP_DOMAIN"
  else
    umask 077
    cat > "$ENV_FILE" <<EOF
# Generated by examples/vps-deploy/scripts/bootstrap.sh on $(date -Iseconds)
PAPERCLIP_DOMAIN=$PAPERCLIP_DOMAIN
PAPERCLIP_PUBLIC_URL=https://$PAPERCLIP_DOMAIN
BETTER_AUTH_SECRET=$better_auth_secret
POSTGRES_PASSWORD=$postgres_password
PAPERCLIP_REF=$PAPERCLIP_REF
POSTGRES_IMAGE=postgres:17.4-alpine
CADDY_IMAGE=caddy:2.8
EOF
    chmod 600 "$ENV_FILE"
  fi
fi

# ---- bring up ---------------------------------------------------------------

log "starting the stack"
run "cd '$DOCKER_DIR' && docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build"

cat <<EOF

Done.

Watch the server come up:

  cd $DOCKER_DIR
  docker compose -f docker-compose.yml -f docker-compose.prod.yml logs -f server

Look for the one-time board-claim URL:

  [claim] /board-claim/<token>?code=<code>

Visit https://$PAPERCLIP_DOMAIN/board-claim/<token>?code=<code> in a browser to
become the instance admin. Caddy will request a Let's Encrypt cert on first
hit, so make sure DNS for $PAPERCLIP_DOMAIN points at this VPS.

Provider firewall reminder: only ports 22, 80, 443 should be reachable from
the internet. Ports 3100 (Paperclip) and 5432 (Postgres) MUST stay closed at
the provider edge — the docker-compose overlay binds them to localhost or the
docker network only, but the firewall is the actual perimeter.
EOF
